apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config-map
  namespace: team-blue
data:
  key-generator.sh: |
    #!/bin/sh
    sleep 20
    export VAULT_TOKEN=`cat /tmp/vault-config-deploy/root-keys.txt`
    vault read -field=public_key ssh/config/ca > /etc/ssh/trusted-user-ca-keys.pem
    sleep 1000
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blue-vault-ssh
  namespace: team-blue
  labels:
    k8s-app: blue-vault
spec:
  selector:
    matchLabels:
      name: blue-vault-ssh
  template:
    metadata:
      labels:
        name: blue-vault-ssh
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: eu-central-1b
      containers:
      - image: vault:latest
        name: blue-vault-ssh
        command: ["/bin/sh"]
        args: ["-c","sh /tmp/vault-config/key-generator.sh"]
        env:
        - name: VAULT_ADDR
          value: http://vault.team-blue:8200
        volumeMounts:
        - name: vault-config-map-volume
          mountPath: /tmp/vault-config/
        - name: node-ssh
          mountPath: /etc/ssh/
        - name: vault-persistent-storage
          mountPath: /tmp/vault-config-deploy/
      volumes:
      - name: vault-config-map-volume
        configMap:
          name: vault-config-map
      - name: node-ssh
        hostPath:
          path: /etc/ssh/
          type: Directory
      - name: vault-persistent-storage
        hostPath:
          path: /tmp/
          type: Directory
