apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault:latest
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
        volumeMounts:
        - name: vault-persistent-storage
          mountPath: /usr/share/
      volumes:
      - name: vault-persistent-storage
        hostPath:
          path: /
          type: Directory